### ISSUE TITLE
Notification : duplicate value - Debug Mode

### ISSUE THREAD

**Issue by sebmehr** [moodleuulm/moodle-block_course_overview_campus#12] opened 2016-02-16 20:17 UTC
Hello,

I'm using a Moodle 2.9 site with the last version of your awesome block (Release 2.9 (Build: 2015092900)). I've noticed on particular user, i got an error when i turn on debug messages. Here is one example : 

![debug-cooc](https://cloud.githubusercontent.com/assets/12945028/13089221/c95c4bbc-d493-11e5-865e-b0c97712c951.PNG)

And this is our configuration's block : 

![conf-cooc](https://cloud.githubusercontent.com/assets/12945028/13089639/adb8b81c-d495-11e5-85a5-9faae4ab82f7.PNG)

I've applied a var_dump function on the $courseteachers var and this is the output of the interesting line : 

`[847]=> object(stdClass)#2171 (5) { ["id"]=> string(3) "847" ["lastname"]=> string(7) "Doe" ["firstname"]=> string(8) "Jane" ["sortorder"]=> string(1) "3" ["roleid"]=> string(1) "3" }`

Do you have any idea to fix the problem ?

Thanks in advance for your help !

Seb

**Comment by abias** [comment] 2016-02-17 22:57
Hi Seb,

I have seen this message before, but had no time to fix the problem. Frankly speaking, it should not be a real problem as it is just an indication that Moodle removed duplicate entries of the same teacher, but in the end the course list was fine in my case.

To check if your scenario matches mine and to hopefully remove the message, can you send me a screenshot or list of the user's course list in the block and of the content of the teacher filter in the block?

Thanks,
Alex

**Comment by sebmehr** [comment] 2016-02-26 04:49
Hi Alexander,

thanks for your reply ! 

You'll find attach to this message two files : one with the course list and one with teachers.

[teachers.xlsx](https://github.com/moodleuulm/moodle-block_course_overview_campus/files/147682/teachers.xlsx)
[courses.xlsx](https://github.com/moodleuulm/moodle-block_course_overview_campus/files/147683/courses.xlsx)

The one with the id 847 is Florence Bolo.

Seb

**Comment by abias** [comment] 2016-02-28 21:21
Hi Seb,

thanks for the files. Unfortunately, they don't really help my to isolate the problem.

However, I did some more tests. I was able to trigger the debug message you have raised in two cases. Steps to reproduce:

Case 1:
* Set setting "block_course_overview_campus | secondrowshowteachername" to On OR set setting "block_course_overview_campus | teachercoursefilter" to On
* Set setting "block_course_overview_campus | teacherroles" to more than one teacher role
* Make sure that there is at least one user who has more than one of these roles in the same course

Case 2:
* Set setting "block_course_overview_campus | secondrowshowteachername" to On OR set setting "block_course_overview_campus | teachercoursefilter" to On
* Set setting "block_course_overview_campus | teacherrolesparent" to Yes
* Set setting "block_course_overview_campus | teacherroles" to at least one teacher role
* Make sure that there is at least one user who has this role assigned in course context AND at the same time assigned the same role in a higher context (category context or system context).

In both cases, the get_role_users() function calls in line 442 / 446 / 450 / 454 of block_course_overview_campus.php will produce duplicate results which the debug message is complaining about (but the duplicate results will be eliminated before the function call returns its results). I am confused that this happens at all because I ask for the "ra.id" field which should produce unique result items...

Seb, can you confirm that your case with Florence Bolo matches case 1 or case 2?

Thanks,
Alex

**Comment by sebmehr** [comment] 2016-02-29 19:20
Hi Alexander,

Thanks for the test and all these informations. I haven't access to the platform until mid-march. I'll keep you in touch asap.

Seb

**Comment by sebmehr** [comment] 2016-03-30 00:51
Hi Alexander,

I have some news about this debug message. I tried the two cases with an other user and both produce the debug message but Florence Bolo doesn't match with these scenarios.

So, I checked in the database every enrolmnents concerning her and i've found something interesting. One of the course in the list uses course meta link enrolment methods and in both courses (parent and child) she has the teacher role. when i disable this enrolment method, the message disappears.

I haven't noticed this before because in the course meta link's options we don't synchronize teacher and non-editing teacher role. Despite this, it seems Moodle record this enrolment in the database so that could explain the duplicate entry in your query.

Seb

**Comment by janeklb** [comment] 2016-04-12 11:06
@sebmehr, which minor version of 2.9 are you using? Also, what database (postgres, mysql, etc.) is your Moodle running on?

**Comment by sebmehr** [comment] 2016-04-12 19:00
Hello,

when i wrote my first message i was running a Moodle 2.9 but now i'm in 2.9.4+ with a Mysql database.

Seb

**Comment by janeklb** [comment] 2016-04-13 08:15
@sebmehr thanks - I'll have a deeper look

**Comment by abias** [comment] 2017-03-16 10:45
Hi all,

please note that this problem is fixed now thanks to @davosmith in the latest version here on Github, but it will take some more days until a new release with the fix is available in the Moodle plugin repo.

Alex

**Closed by abias** 2017-03-16 10:45 UTC
